version: '2.2'
services:
  mongo:
    scale: 3
    image: mongo:4
    command: ["--replSet", "rs0"]
    volumes:
      - ./rs-init:/rs-init
      - ./init-data:/init-data
networks:
  default:
    name: mongo-network