version: '2.2'
services:
  mongo:
    scale: 3
    image: mongo:4
    command: ["--replSet", "rs0"]
    volumes:
      - ./rs-init:/rs-init
      - ./init-data:/init-data
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    name: mongo-network